version: '3'
services:
  dev-assignment-be:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/transferz
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=transferz
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - 'postgres:/var/lib/postgresql/data'
volumes:
  postgres: